## Stage 1: Build
FROM node:24-alpine AS builder
WORKDIR /app
ENV TZ=Asia/Bangkok
ENV NEXT_TELEMETRY_DISABLED=1
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

## Stage 2: Run
FROM node:24-alpine AS runner
WORKDIR /app
ENV TZ=Asia/Bangkok
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
EXPOSE 3000
ENV PORT=3000
CMD ["node", "server.js"]